[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    adafruit/Adafruit_VL53L0X
    electroniccats/MPU6050
    madhephaestus/ESP32Servo
